/**
 * AGENT 2 — mockData.ts
 * Offline development data, seeded directly from content/signs.json
 * and content/topics.json (created by Agent 1).
 *
 * This file enables full app development WITHOUT a Supabase connection.
 * All functions in api.ts fall back to this data when USE_MOCK = true.
 *
 * The mock data mirrors the exact shape of the Supabase DB rows,
 * with Storage URLs replaced by local asset paths.
 */

import { DBTopic, DBSign, DBQuestion, getStorageUrl, BUCKETS } from './supabaseClient';

// ─── Import Agent 1 content ───────────────────────────────────────────────────
// These JSON files are generated by Agent 1 and used here directly.
// In production they are uploaded to Supabase; in dev we use them as-is.

// eslint-disable-next-line @typescript-eslint/no-var-requires
const rawTopics: RawTopic[] = require('../content/topics.json');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const rawSigns: RawSign[]   = require('../content/signs.json');

// ─── Raw types (from Agent 1 JSON) ───────────────────────────────────────────

interface RawTopic {
  id: string;
  name_amharic: string;
  name_hebrew: string;
  icon: string;
  color: string;
  description_amharic: string;
  audio_intro: string;
  sign_count: number;
  display_order: number;
}

interface RawAnswer {
  id: string;
  text_amharic: string;
  image: string;
  is_correct: boolean;
}

interface RawQuestion {
  id: string;
  question_amharic: string;
  question_audio: string;
  answers: RawAnswer[];
  explanation_correct_amharic: string;
  explanation_wrong_amharic: string;
  explanation_correct_audio: string;
  explanation_wrong_audio: string;
}

interface RawSign {
  id: string;
  topic_id: string;
  order: number;
  image_filename: string;
  video_filename: string;
  name_hebrew: string;
  name_amharic: string;
  explanation_amharic: string;
  audio_name_filename: string;
  audio_explanation_filename: string;
  questions: RawQuestion[];
}

// ─── Transform helpers ────────────────────────────────────────────────────────

/**
 * Use Supabase Storage CDN URLs so images/audio/video load in both
 * mock mode and production. All content is already uploaded to Supabase.
 */
function localAudio(filename: string): string {
  return getStorageUrl(BUCKETS.AUDIO, filename);
}

function localImage(filename: string): string {
  return getStorageUrl(BUCKETS.IMAGES, filename);
}

function localVideo(filename: string): string {
  return getStorageUrl(BUCKETS.VIDEOS, filename);
}

// ─── Transformed mock data ────────────────────────────────────────────────────

/**
 * Topics: mapped from Agent 1 JSON → DBTopic shape
 */
export const topics: DBTopic[] = rawTopics.map(t => ({
  id:                   t.id,
  name_amharic:         t.name_amharic,
  name_hebrew:          t.name_hebrew,
  icon:                 t.icon,
  color:                t.color,
  description_amharic:  t.description_amharic,
  audio_intro_url:      localAudio(t.audio_intro),
  sign_count:           t.sign_count,
  display_order:        t.display_order,
}));

/**
 * Signs: mapped from Agent 1 JSON → DBSign shape
 */
export const signs: DBSign[] = rawSigns.map(s => ({
  id:                       s.id,
  topic_id:                 s.topic_id,
  display_order:            s.order,
  name_amharic:             s.name_amharic,
  name_hebrew:              s.name_hebrew,
  explanation_amharic:      s.explanation_amharic,
  image_url:                localImage(s.image_filename),
  video_url:                localVideo(s.video_filename),
  audio_name_url:           localAudio(s.audio_name_filename),
  audio_explanation_url:    localAudio(s.audio_explanation_filename),
  difficulty:               1,
}));

/**
 * Questions: flattened from all signs → DBQuestion shape
 * Only 4-answer questions are included (3-answer questions are old/outdated data).
 */
export const questions: DBQuestion[] = rawSigns.flatMap(sign =>
  sign.questions
    .filter(q => q.answers.length >= 4)
    .map(q => ({
    id:                             q.id,
    sign_id:                        sign.id,
    topic_id:                       sign.topic_id,
    question_amharic:               q.question_amharic,
    question_audio_url:             localAudio(q.question_audio),
    answers: q.answers.map(a => ({
      id:             a.id as 'A' | 'B' | 'C',
      text_amharic:   a.text_amharic,
      image_url:      a.image ? localImage(a.image) : undefined,
      audio_url:      localAudio(`answer_${q.id}_${a.id}.mp3`),
      is_correct:     a.is_correct,
    })),
    explanation_correct_amharic:    q.explanation_correct_amharic,
    explanation_wrong_amharic:      q.explanation_wrong_amharic,
    explanation_correct_audio_url:  localAudio(q.explanation_correct_audio),
    explanation_wrong_audio_url:    localAudio(q.explanation_wrong_audio),
    difficulty:                     1,
  }))
);

// ─── Convenience lookups ──────────────────────────────────────────────────────

/** Map: sign.id → sign */
export const signsById: Map<string, DBSign> = new Map(signs.map(s => [s.id, s]));

/** Map: question.id → question */
export const questionsById: Map<string, DBQuestion> = new Map(questions.map(q => [q.id, q]));

/** Map: topic.id → signs[] */
export const signsByTopic: Map<string, DBSign[]> = new Map(
  topics.map(t => [t.id, signs.filter(s => s.topic_id === t.id)])
);

/** Map: sign.id → questions[] */
export const questionsBySign: Map<string, DBQuestion[]> = new Map(
  signs.map(s => [s.id, questions.filter(q => q.sign_id === s.id)])
);

// ─── Mock exam question generator ─────────────────────────────────────────────

/**
 * Returns a random balanced set of questions across all topics.
 * Mirrors the get_random_questions SQL stored procedure.
 */
export function getRandomExamQuestions(count: number = 30): DBQuestion[] {
  const perTopic = Math.ceil(count / topics.length);
  const selected: DBQuestion[] = [];

  for (const topic of topics) {
    const topicQs = questions.filter(q => q.topic_id === topic.id);
    const shuffled = [...topicQs].sort(() => Math.random() - 0.5);
    selected.push(...shuffled.slice(0, perTopic));
  }

  return selected.sort(() => Math.random() - 0.5).slice(0, count);
}

// ─── Stats ────────────────────────────────────────────────────────────────────

console.info(
  `[mockData] Loaded: ${topics.length} topics, ${signs.length} signs, ${questions.length} questions`
);
