/**
 * buildRoadScenarioDiagram.mjs
 *
 * Draws the road-scene diagrams used by behavioural subtopics, and rasterises
 * each one to PNG ready for upload.
 *
 * Why drawn rather than generated by an image model: in these subtopics the
 * picture IS the question. If the green arrow lands on the wrong car, the
 * learner is taught the opposite of the law. Every coordinate here is
 * deliberate, so the arrow cannot drift between one diagram and the next. It
 * also keeps a scene near 70 KB rather than the several hundred an image model
 * returns, which matters on the phones these learners actually use.
 *
 * Why PNG as well as SVG: React Native's <Image> cannot render SVG and the app
 * does not bundle react-native-svg. The SVG stays the source of truth; the PNG
 * is what ships. Change a colour or an arrow here, re-run, re-upload.
 *
 * Lane sides follow RIGHT-HAND traffic. Northbound keeps to the east half of
 * the road, southbound to the west. Those two positions are named constants
 * rather than raw numbers on purpose: the first draft of this diagram had the
 * cars on the wrong sides, which reads as British traffic and quietly teaches
 * the wrong road position.
 *
 * Usage:
 *   node scripts/buildRoadScenarioDiagram.mjs
 *   node scripts/buildRoadScenarioDiagram.mjs --out <directory>
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const require    = createRequire(import.meta.url);
const __dirname  = dirname(fileURLToPath(import.meta.url));
const ROOT       = join(__dirname, '..');

// ─── Palette ──────────────────────────────────────────────────────────────────

const C = {
  grass:  '#7cc576',
  road:   '#5b6169',
  kerb:   '#e5e7eb',
  line:   '#f8fafc',
  go:     '#15803d',   // the vehicle with priority
  wait:   '#b91c1c',   // the vehicle that must give way
  glass:  '#cfe8f5',
  badge:  '#111827',
  tyre:   '#1f2937',
};

/** Car body colours, each with a matching darker outline. */
const CARS = {
  yellow: { body: '#f2b705', edge: '#8a6a00' },
  green:  { body: '#1f9d55', edge: '#0b5c31' },
  blue:   { body: '#2563eb', edge: '#12327a' },
  white:  { body: '#f1f5f9', edge: '#64748b' },
  red:    { body: '#dc2626', edge: '#7f1d1d' },
  silver: { body: '#cbd5e1', edge: '#64748b' },
};

// ─── Car ──────────────────────────────────────────────────────────────────────

/**
 * A car seen from above, drawn nose-up and then rotated into place.
 *
 * @param x,y      centre of the car
 * @param heading  degrees clockwise; 0 = nose up (north), 90 = nose right
 * @param colour   key of CARS
 * @param indicate 'left' | 'right' | null — lights that indicator
 * @param scale    1 is a car roughly 56x104
 */
function car({ x, y, heading = 0, colour = 'white', indicate = null, scale = 1 }) {
  const { body, edge } = CARS[colour] ?? CARS.white;

  // Nose at y=-52, tail at y=+52, narrower at the front like a real car seen
  // from above — that taper is what stops it reading as a plain rectangle.
  const outline = 'M 0,-52 C 13,-52 23,-47 25,-38 L 27,28 C 27,42 21,52 10,52 '
                + 'L -10,52 C -21,52 -27,42 -27,28 L -25,-38 C -23,-47 -13,-52 0,-52 Z';

  const indicator = side => {
    if (indicate !== side) return '';
    const ix = side === 'left' ? -21 : 21;
    return `<circle cx="${ix}" cy="-44" r="6.5" fill="#ff8c00" stroke="${edge}" stroke-width="1.5"/>`
         + `<circle cx="${ix}" cy="-44" r="11" fill="none" stroke="#ff8c00" stroke-width="2" opacity="0.5"/>`;
  };

  return `
  <g transform="translate(${x} ${y}) rotate(${heading}) scale(${scale})">
    <g fill="${C.tyre}">
      <rect x="-31" y="-34" width="9" height="22" rx="4"/>
      <rect x="22"  y="-34" width="9" height="22" rx="4"/>
      <rect x="-31" y="12"  width="9" height="22" rx="4"/>
      <rect x="22"  y="12"  width="9" height="22" rx="4"/>
    </g>

    <path d="${outline}" fill="${body}" stroke="${edge}" stroke-width="3" stroke-linejoin="round"/>

    <rect x="-31" y="-24" width="6" height="9" rx="2.5" fill="${body}" stroke="${edge}" stroke-width="1.5"/>
    <rect x="25"  y="-24" width="6" height="9" rx="2.5" fill="${body}" stroke="${edge}" stroke-width="1.5"/>

    <path d="M -17,-26 L 17,-26 L 14,-12 L -14,-12 Z" fill="${C.glass}"/>
    <rect x="-15" y="-12" width="30" height="26" rx="3" fill="${body}" stroke="${edge}" stroke-width="1.5"/>
    <path d="M -14,14 L 14,14 L 17,27 L -17,27 Z" fill="${C.glass}"/>

    <rect x="-19" y="-50" width="11" height="6" rx="3" fill="#fff8dc" stroke="${edge}" stroke-width="1.2"/>
    <rect x="8"   y="-50" width="11" height="6" rx="3" fill="#fff8dc" stroke="${edge}" stroke-width="1.2"/>
    <rect x="-19" y="44"  width="11" height="6" rx="3" fill="#ef4444" stroke="${edge}" stroke-width="1.2"/>
    <rect x="8"   y="44"  width="11" height="6" rx="3" fill="#ef4444" stroke="${edge}" stroke-width="1.2"/>

    ${indicator('left')}${indicator('right')}
  </g>`;
}

/** The numbered disc that lets a spoken question say "car number two". */
function badge({ x, y, n }) {
  return `
  <g>
    <circle cx="${x}" cy="${y}" r="16" fill="${C.badge}"/>
    <text x="${x}" y="${y + 6}" font-family="Arial, Helvetica, sans-serif" font-size="19"
          font-weight="bold" fill="#ffffff" text-anchor="middle">${n}</text>
  </g>`;
}

function tree({ x, y, r = 32 }) {
  return `<circle cx="${x}" cy="${y}" r="${r}" fill="#3f9142"/>`
       + `<rect x="${x - 5}" y="${y + r - 4}" width="10" height="22" fill="#6b4a2f"/>`;
}

/** A movement arrow. `priority` picks green "goes first" or red "must wait". */
function arrow({ d, priority = true }) {
  const col = priority ? C.go : C.wait;
  const mk  = priority ? 'headGo' : 'headWait';
  return `<path d="${d}" fill="none" stroke="${col}" stroke-width="11"
            stroke-linecap="round" stroke-linejoin="round" marker-end="url(#${mk})"/>`;
}

// ─── Scene: a plain four-way crossroads ───────────────────────────────────────

const W = 640, H = 440;
const RX = 238, RW = 164;          // vertical road
const RY = 150, RH = 164;          // horizontal road

const CENTRE_X = RX + RW / 2;      // 320
const CENTRE_Y = RY + RH / 2;      // 232

// Right-hand traffic: a car heading up keeps to the east half, one heading down
// to the west half, one heading left to the north half.
const NORTHBOUND_X = CENTRE_X + 40;
const SOUTHBOUND_X = CENTRE_X - 40;
const WESTBOUND_Y  = CENTRE_Y - 42;

function crossroads() {
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <g fill="${C.road}">
    <rect x="${RX}" y="0" width="${RW}" height="${H}"/>
    <rect x="0" y="${RY}" width="${W}" height="${RH}"/>
  </g>
  <g fill="${C.kerb}">
    <rect x="${RX - 6}" y="0" width="6" height="${RY}"/><rect x="${RX + RW}" y="0" width="6" height="${RY}"/>
    <rect x="${RX - 6}" y="${RY + RH}" width="6" height="${H - RY - RH}"/><rect x="${RX + RW}" y="${RY + RH}" width="6" height="${H - RY - RH}"/>
    <rect x="0" y="${RY - 6}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${RY - 6}" width="${W - RX - RW - 6}" height="6"/>
    <rect x="0" y="${RY + RH}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${RY + RH}" width="${W - RX - RW - 6}" height="6"/>
  </g>
  <g stroke="${C.line}" stroke-width="4" stroke-dasharray="22 18">
    <line x1="${CENTRE_X}" y1="8" x2="${CENTRE_X}" y2="${RY - 10}"/>
    <line x1="${CENTRE_X}" y1="${RY + RH + 10}" x2="${CENTRE_X}" y2="${H - 8}"/>
    <line x1="8" y1="${CENTRE_Y}" x2="${RX - 10}" y2="${CENTRE_Y}"/>
    <line x1="${RX + RW + 10}" y1="${CENTRE_Y}" x2="${W - 8}" y2="${CENTRE_Y}"/>
  </g>
  ${tree({ x: 120, y: 80 })}${tree({ x: 520, y: 88, r: 28 })}
  ${tree({ x: 128, y: 372, r: 28 })}${tree({ x: 524, y: 366 })}`;
}

function svg(inner, label) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="${label}">
  <defs>
    <marker id="headGo" viewBox="0 0 12 12" refX="9" refY="6" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
      <path d="M0,1 L11,6 L0,11 Z" fill="${C.go}"/>
    </marker>
    <marker id="headWait" viewBox="0 0 12 12" refX="9" refY="6" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
      <path d="M0,1 L11,6 L0,11 Z" fill="${C.wait}"/>
    </marker>
  </defs>${inner}
</svg>
`;
}

// ─── tr_l1_s3 — turning left across an oncoming car ───────────────────────────
// Car 1 comes up from the south wanting to turn left. Car 2 comes down from the
// north going straight, and has priority. The two arrows deliberately cross:
// that intersection point is the whole reason car 1 must wait, and it is
// visible on screen.

const scene = crossroads()
  + car({ x: NORTHBOUND_X, y: 368, heading: 0,   colour: 'yellow', indicate: 'left' })
  + car({ x: SOUTHBOUND_X, y: 96,  heading: 180, colour: 'blue' })
  // arrows before badges, so a badge is never buried under an arrow head
  + arrow({ d: `M ${SOUTHBOUND_X},150 L ${SOUTHBOUND_X},322`, priority: true })
  + arrow({
      d: `M ${NORTHBOUND_X},312 L ${NORTHBOUND_X},${WESTBOUND_Y + 34} `
       + `Q ${NORTHBOUND_X},${WESTBOUND_Y} ${NORTHBOUND_X - 44},${WESTBOUND_Y} `
       + `L 196,${WESTBOUND_Y}`,
      priority: false,
    })
  // badges sit on the verge beside their car, clear of arrows and bodywork
  + badge({ x: NORTHBOUND_X + 62, y: 368, n: 1 })
  + badge({ x: SOUTHBOUND_X - 62, y: 96,  n: 2 });

// ─── Write SVG, then rasterise ────────────────────────────────────────────────

const outArg  = process.argv.indexOf('--out');
const OUT_DIR = outArg >= 0 ? process.argv[outArg + 1] : join(ROOT, 'temp_behavioral');
const NAME    = 'tr_l1_s3_left_turn_vs_oncoming';

const svgText = svg(scene, 'Crossroads: a car turning left gives way to an oncoming car going straight');
const svgPath = join(OUT_DIR, `${NAME}.svg`);
writeFileSync(svgPath, svgText, 'utf8');
console.log(`SVG: ${svgPath}`);

// 2x so it stays crisp on a phone screen
const { loadImage, createCanvas } = require('canvas');
const img    = await loadImage(Buffer.from(svgText, 'utf8'));
const canvas = createCanvas(img.width * 2, img.height * 2);
canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
const png     = canvas.toBuffer('image/png');
const pngPath = join(OUT_DIR, `${NAME}.png`);
writeFileSync(pngPath, png);
console.log(`PNG: ${pngPath}  (${canvas.width}x${canvas.height}, ${(png.length / 1024).toFixed(1)} KB)`);
