/**
 * buildRoadScenarioDiagram.mjs
 *
 * Draws the road-scene diagrams used by behavioural subtopics, and rasterises
 * each one to PNG ready for upload.
 *
 * Why drawn rather than generated by an image model: in these subtopics the
 * picture IS the question. If the green arrow lands on the wrong car, the
 * learner is taught the opposite of the law. Every coordinate here is
 * deliberate, so the arrow cannot drift between one diagram and the next. It
 * also keeps a scene near 70 KB rather than the several hundred an image model
 * returns, which matters on the phones these learners actually use.
 *
 * Why PNG as well as SVG: React Native's <Image> cannot render SVG and the app
 * does not bundle react-native-svg. The SVG stays the source of truth; the PNG
 * is what ships. Change a colour or an arrow here, re-run, re-upload.
 *
 * Lane sides follow RIGHT-HAND traffic. Northbound keeps to the east half of
 * the road, southbound to the west. Those two positions are named constants
 * rather than raw numbers on purpose: the first draft of this diagram had the
 * cars on the wrong sides, which reads as British traffic and quietly teaches
 * the wrong road position.
 *
 * Usage:
 *   node scripts/buildRoadScenarioDiagram.mjs
 *   node scripts/buildRoadScenarioDiagram.mjs --out <directory>
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const require    = createRequire(import.meta.url);
const __dirname  = dirname(fileURLToPath(import.meta.url));
const ROOT       = join(__dirname, '..');

// ─── Palette ──────────────────────────────────────────────────────────────────

const C = {
  grass:  '#7cc576',
  road:   '#5b6169',
  kerb:   '#e5e7eb',
  line:   '#f8fafc',
  go:     '#15803d',   // the vehicle with priority
  wait:   '#b91c1c',   // the vehicle that must give way
  glass:  '#cfe8f5',
  badge:  '#111827',
  tyre:   '#1f2937',
};

/** Car body colours, each with a matching darker outline. */
const CARS = {
  yellow: { body: '#f2b705', edge: '#8a6a00' },
  green:  { body: '#1f9d55', edge: '#0b5c31' },
  blue:   { body: '#2563eb', edge: '#12327a' },
  white:  { body: '#f1f5f9', edge: '#64748b' },
  red:    { body: '#dc2626', edge: '#7f1d1d' },
  silver: { body: '#cbd5e1', edge: '#64748b' },
};

// ─── Car ──────────────────────────────────────────────────────────────────────

/**
 * A car seen from above, drawn nose-up and then rotated into place.
 *
 * @param x,y      centre of the car
 * @param heading  degrees clockwise; 0 = nose up (north), 90 = nose right
 * @param colour   key of CARS
 * @param indicate 'left' | 'right' | null — lights that indicator
 * @param scale    1 is a car roughly 56x104
 */
function car({ x, y, heading = 0, colour = 'white', indicate = null, scale = 1 }) {
  const { body, edge } = CARS[colour] ?? CARS.white;

  // Nose at y=-52, tail at y=+52, narrower at the front like a real car seen
  // from above — that taper is what stops it reading as a plain rectangle.
  const outline = 'M 0,-52 C 13,-52 23,-47 25,-38 L 27,28 C 27,42 21,52 10,52 '
                + 'L -10,52 C -21,52 -27,42 -27,28 L -25,-38 C -23,-47 -13,-52 0,-52 Z';

  const indicator = side => {
    if (indicate !== side) return '';
    const ix = side === 'left' ? -21 : 21;
    return `<circle cx="${ix}" cy="-44" r="6.5" fill="#ff8c00" stroke="${edge}" stroke-width="1.5"/>`
         + `<circle cx="${ix}" cy="-44" r="11" fill="none" stroke="#ff8c00" stroke-width="2" opacity="0.5"/>`;
  };

  return `
  <g transform="translate(${x} ${y}) rotate(${heading}) scale(${scale})">
    <g fill="${C.tyre}">
      <rect x="-31" y="-34" width="9" height="22" rx="4"/>
      <rect x="22"  y="-34" width="9" height="22" rx="4"/>
      <rect x="-31" y="12"  width="9" height="22" rx="4"/>
      <rect x="22"  y="12"  width="9" height="22" rx="4"/>
    </g>

    <path d="${outline}" fill="${body}" stroke="${edge}" stroke-width="3" stroke-linejoin="round"/>

    <rect x="-31" y="-24" width="6" height="9" rx="2.5" fill="${body}" stroke="${edge}" stroke-width="1.5"/>
    <rect x="25"  y="-24" width="6" height="9" rx="2.5" fill="${body}" stroke="${edge}" stroke-width="1.5"/>

    <path d="M -17,-26 L 17,-26 L 14,-12 L -14,-12 Z" fill="${C.glass}"/>
    <rect x="-15" y="-12" width="30" height="26" rx="3" fill="${body}" stroke="${edge}" stroke-width="1.5"/>
    <path d="M -14,14 L 14,14 L 17,27 L -17,27 Z" fill="${C.glass}"/>

    <rect x="-19" y="-50" width="11" height="6" rx="3" fill="#fff8dc" stroke="${edge}" stroke-width="1.2"/>
    <rect x="8"   y="-50" width="11" height="6" rx="3" fill="#fff8dc" stroke="${edge}" stroke-width="1.2"/>
    <rect x="-19" y="44"  width="11" height="6" rx="3" fill="#ef4444" stroke="${edge}" stroke-width="1.2"/>
    <rect x="8"   y="44"  width="11" height="6" rx="3" fill="#ef4444" stroke="${edge}" stroke-width="1.2"/>

    ${indicator('left')}${indicator('right')}
  </g>`;
}


/** The numbered disc that lets a spoken question say "car number two". */
function badge({ x, y, n }) {
  return `
  <g>
    <circle cx="${x}" cy="${y}" r="16" fill="${C.badge}"/>
    <text x="${x}" y="${y + 6}" font-family="Arial, Helvetica, sans-serif" font-size="19"
          font-weight="bold" fill="#ffffff" text-anchor="middle">${n}</text>
  </g>`;
}

/**
 * A give-way sign on its post: a downward-pointing triangle, red rim, pale
 * centre.
 *
 * ⚠️ No lettering, ever. The app is used by Amharic speakers across many
 * countries and a word painted on a sign is a word most of its learners cannot
 * read — the shape and the colour have to carry the whole meaning, exactly as
 * they do on a real road. The narration says what the sign means; the picture
 * only shows what it looks like.
 */
function giveWaySign({ x, y, scale = 1 }) {
  return `
  <g transform="translate(${x} ${y}) scale(${scale})">
    <rect x="-3" y="0" width="6" height="46" fill="#9ca3af" stroke="#6b7280" stroke-width="1.5"/>
    <path d="M -30,-46 L 30,-46 L 0,4 Z" fill="#ffffff" stroke="#c81e1e" stroke-width="9" stroke-linejoin="round"/>
  </g>`;
}

function tree({ x, y, r = 32 }) {
  return `<circle cx="${x}" cy="${y}" r="${r}" fill="#3f9142"/>`
       + `<rect x="${x - 5}" y="${y + r - 4}" width="10" height="22" fill="#6b4a2f"/>`;
}

/** A movement arrow. `priority` picks green "goes first" or red "must wait". */
function arrow({ d, priority = true }) {
  const col = priority ? C.go : C.wait;
  const mk  = priority ? 'headGo' : 'headWait';
  return `<path d="${d}" fill="none" stroke="${col}" stroke-width="11"
            stroke-linecap="round" stroke-linejoin="round" marker-end="url(#${mk})"/>`;
}

// ─── Scene: a plain four-way crossroads ───────────────────────────────────────

const W = 640, H = 440;
const RX = 238, RW = 164;          // vertical road
const RY = 150, RH = 164;          // horizontal road

const CENTRE_X = RX + RW / 2;      // 320
const CENTRE_Y = RY + RH / 2;      // 232

// Right-hand traffic: a car heading up keeps to the east half, one heading down
// to the west half, one heading left to the north half.
const NORTHBOUND_X = CENTRE_X + 40;
const SOUTHBOUND_X = CENTRE_X - 40;
const WESTBOUND_Y  = CENTRE_Y - 42;
const EASTBOUND_Y  = CENTRE_Y + 42;

function crossroads() {
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <g fill="${C.road}">
    <rect x="${RX}" y="0" width="${RW}" height="${H}"/>
    <rect x="0" y="${RY}" width="${W}" height="${RH}"/>
  </g>
  <g fill="${C.kerb}">
    <rect x="${RX - 6}" y="0" width="6" height="${RY}"/><rect x="${RX + RW}" y="0" width="6" height="${RY}"/>
    <rect x="${RX - 6}" y="${RY + RH}" width="6" height="${H - RY - RH}"/><rect x="${RX + RW}" y="${RY + RH}" width="6" height="${H - RY - RH}"/>
    <rect x="0" y="${RY - 6}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${RY - 6}" width="${W - RX - RW - 6}" height="6"/>
    <rect x="0" y="${RY + RH}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${RY + RH}" width="${W - RX - RW - 6}" height="6"/>
  </g>
  <g stroke="${C.line}" stroke-width="4" stroke-dasharray="22 18">
    <line x1="${CENTRE_X}" y1="8" x2="${CENTRE_X}" y2="${RY - 10}"/>
    <line x1="${CENTRE_X}" y1="${RY + RH + 10}" x2="${CENTRE_X}" y2="${H - 8}"/>
    <line x1="8" y1="${CENTRE_Y}" x2="${RX - 10}" y2="${CENTRE_Y}"/>
    <line x1="${RX + RW + 10}" y1="${CENTRE_Y}" x2="${W - 8}" y2="${CENTRE_Y}"/>
  </g>
  ${tree({ x: 120, y: 80 })}${tree({ x: 520, y: 88, r: 28 })}
  ${tree({ x: 128, y: 372, r: 28 })}${tree({ x: 524, y: 366 })}`;
}

// ─── Scene: a T junction ──────────────────────────────────────────────────────
//
// A different shape of junction, not another dressing of the crossroads: the
// side road ends at the main road instead of crossing it. It also settles a
// question a four-way crossroads leaves open — which road a sign belongs to.
// On the stem of a T the sign stands right beside the car it faces, on that
// car's own right-hand verge, and cannot be read as belonging to anything else.

const TEE_STEM_TOP = RY + RH;              // the side road starts at the main road

function teeJunction() {
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <g fill="${C.road}">
    <rect x="0" y="${RY}" width="${W}" height="${RH}"/>
    <rect x="${RX}" y="${TEE_STEM_TOP}" width="${RW}" height="${H - TEE_STEM_TOP}"/>
  </g>
  <g fill="${C.kerb}">
    <rect x="0" y="${RY - 6}" width="${W}" height="6"/>
    <rect x="0" y="${RY + RH}" width="${RX - 6}" height="6"/>
    <rect x="${RX + RW + 6}" y="${RY + RH}" width="${W - RX - RW - 6}" height="6"/>
    <rect x="${RX - 6}" y="${TEE_STEM_TOP}" width="6" height="${H - TEE_STEM_TOP}"/>
    <rect x="${RX + RW}" y="${TEE_STEM_TOP}" width="6" height="${H - TEE_STEM_TOP}"/>
  </g>
  <g stroke="${C.line}" stroke-width="4" stroke-dasharray="22 18">
    <line x1="8" y1="${CENTRE_Y}" x2="${RX - 10}" y2="${CENTRE_Y}"/>
    <line x1="${RX + RW + 10}" y1="${CENTRE_Y}" x2="${W - 8}" y2="${CENTRE_Y}"/>
    <line x1="${CENTRE_X}" y1="${TEE_STEM_TOP + 12}" x2="${CENTRE_X}" y2="${H - 8}"/>
  </g>
  ${tree({ x: 108, y: 74 })}${tree({ x: 300, y: 66, r: 26 })}${tree({ x: 520, y: 78, r: 28 })}
  ${tree({ x: 96, y: 392, r: 30 })}${tree({ x: 552, y: 386, r: 26 })}`;
}

// ─── Scene: an open two-way road, no junction ─────────────────────────────────
//
// Overtaking is not a junction problem, so these cards drop the crossroads
// entirely. What matters instead is the pair of lines down the middle: Israeli
// marking puts a solid line and a broken line side by side, and the one NEAREST
// A DRIVER is the one that governs them: broken on their side, they may cross to
// overtake; solid on their side, they may not.
//
// `brokenLine` names which of the two is the broken one by where it sits in the
// picture, 'lower' or 'upper' — NOT by whose side it is on. A card may put the
// overtaking driver in either lane, and a flag named after "our side" silently
// means the opposite one as soon as it does.

const OPEN_RY = 130, OPEN_RH = 180;            // the carriageway: 130..310
const OPEN_CENTRE_Y = OPEN_RY + OPEN_RH / 2;   // 220
const ONCOMING_Y = OPEN_RY + 45;               // 175 — traffic coming towards us
const OURS_Y     = OPEN_RY + OPEN_RH - 45;     // 265 — our side, right-hand traffic
const NEAR_LINE_Y = OPEN_CENTRE_Y + 7;         // the lower of the two centre lines
const FAR_LINE_Y  = OPEN_CENTRE_Y - 7;         // the upper of the two

function openRoad({ brokenLine }) {
  const line = (y, broken) =>
    `<line x1="8" y1="${y}" x2="${W - 8}" y2="${y}" stroke="${C.line}" stroke-width="5"`
    + (broken ? ` stroke-dasharray="26 20"` : '') + `/>`;
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <rect x="0" y="${OPEN_RY}" width="${W}" height="${OPEN_RH}" fill="${C.road}"/>
  <g fill="${C.kerb}">
    <rect x="0" y="${OPEN_RY - 6}" width="${W}" height="6"/>
    <rect x="0" y="${OPEN_RY + OPEN_RH}" width="${W}" height="6"/>
  </g>
  ${line(FAR_LINE_Y, brokenLine === 'upper')}
  ${line(NEAR_LINE_Y, brokenLine === 'lower')}
  ${tree({ x: 90, y: 62, r: 30 })}${tree({ x: 300, y: 54, r: 26 })}${tree({ x: 540, y: 64, r: 28 })}
  ${tree({ x: 120, y: 384, r: 28 })}${tree({ x: 380, y: 392, r: 24 })}${tree({ x: 566, y: 380, r: 30 })}`;
}

// ─── Scene: the road ahead, seen from behind our own car ──────────────────────
//
// Not every situation reads from above. A motorcycle seen from directly
// overhead is mostly the rider's back, and three attempts at drawing one that
// way were still unrecognisable. From BEHIND it is unmistakable: the rider sits
// up, the helmet and the mirrors stand out, and the machine is obviously
// narrow. Same scene, same questions, different viewpoint.
//
// Depth is linear: t runs 0 at the horizon to 1 at the bottom of the picture,
// and everything — lane position and vehicle size — is interpolated on it.

const HORIZON = 150;
const VP_X = 320;                                    // vanishing point
const depthAt = y => (y - HORIZON) / (H - HORIZON);  // 0 far … 1 near
const lerp = (far, near, t) => far + (near - far) * t;

// road edges and the two centre lines, far value then near value
const EDGE_L = [298, 26], EDGE_R = [342, 614];
const MID_L  = [316, 292], MID_R = [324, 348];
const laneOurs     = t => lerp((MID_R[0] + EDGE_R[0]) / 2, (MID_R[1] + EDGE_R[1]) / 2, t);
const laneOncoming = t => lerp((EDGE_L[0] + MID_L[0]) / 2, (EDGE_L[1] + MID_L[1]) / 2, t);

function roadAhead({ brokenLine }) {
  const band = (a, b, fill, extra = '') =>
    `<path d="M ${a[0]},${HORIZON} L ${b[0]},${HORIZON} L ${b[1]},${H} L ${a[1]},${H} Z" fill="${fill}" ${extra}/>`;
  // a centre line drawn in perspective: solid as one band, broken as chunks
  const centreLine = (pair, broken) => {
    if (!broken) return band([pair[0] - 1.5, pair[1] - 3], [pair[0] + 1.5, pair[1] + 3], C.line);
    let out = '';
    for (let i = 0; i < 7; i++) {
      const t0 = Math.pow(i / 7, 1.7), t1 = Math.pow((i + 0.55) / 7, 1.7);
      const y0 = HORIZON + (H - HORIZON) * t0, y1 = HORIZON + (H - HORIZON) * t1;
      const x0 = lerp(pair[0], pair[1], t0), x1 = lerp(pair[0], pair[1], t1);
      const w0 = lerp(1.5, 3, t0), w1 = lerp(1.5, 3, t1);
      out += `<path d="M ${x0 - w0},${y0} L ${x0 + w0},${y0} L ${x1 + w1},${y1} L ${x1 - w1},${y1} Z" fill="${C.line}"/>`;
    }
    return out;
  };
  return `
  <rect width="${W}" height="${HORIZON}" fill="#bfe3f5"/>
  <rect y="${HORIZON}" width="${W}" height="${H - HORIZON}" fill="${C.grass}"/>
  ${band(EDGE_L, EDGE_R, C.road)}
  ${band([EDGE_L[0] - 2, EDGE_L[1] - 10], [EDGE_L[0] + 2, EDGE_L[1] + 10], C.kerb)}
  ${band([EDGE_R[0] - 2, EDGE_R[1] - 10], [EDGE_R[0] + 2, EDGE_R[1] + 10], C.kerb)}
  ${centreLine(MID_L, brokenLine === 'left')}
  ${centreLine(MID_R, brokenLine === 'lower' || brokenLine === 'right')}
  <circle cx="96" cy="${HORIZON - 26}" r="26" fill="#3f9142"/><rect x="91" y="${HORIZON - 6}" width="10" height="12" fill="#6b4a2f"/>
  <circle cx="556" cy="${HORIZON - 30}" r="30" fill="#3f9142"/><rect x="551" y="${HORIZON - 6}" width="10" height="14" fill="#6b4a2f"/>`;
}

/** A car seen from behind, sized by how far away it is. */
function carRear({ x, y, w, colour = 'white' }) {
  const { body, edge } = CARS[colour] ?? CARS.white;
  const h = w * 0.78, k = w / 100;
  return `
  <g transform="translate(${x} ${y}) scale(${k})">
    <rect x="-52" y="-30" width="14" height="34" rx="4" fill="${C.tyre}"/>
    <rect x="38"  y="-30" width="14" height="34" rx="4" fill="${C.tyre}"/>
    <path d="M -44,0 L -40,-52 C -38,-62 -30,-66 0,-66 C 30,-66 38,-62 40,-52 L 44,0 Z"
          fill="${body}" stroke="${edge}" stroke-width="3.5" stroke-linejoin="round"/>
    <path d="M -31,-52 C -30,-58 -24,-60 0,-60 C 24,-60 30,-58 31,-52 L 33,-30 L -33,-30 Z" fill="${C.glass}"/>
    <rect x="-44" y="-10" width="88" height="10" rx="3" fill="${edge}"/>
    <rect x="-38" y="-26" width="17" height="11" rx="3" fill="#ef4444"/>
    <rect x="21"  y="-26" width="17" height="11" rx="3" fill="#ef4444"/>
    <rect x="-14" y="-8"  width="28" height="7"  rx="2" fill="#e5e7eb"/>
  </g>`;
}

/**
 * A motorcycle seen from behind, sized by how far away it is. From here the
 * things that identify it are unmissable — the rider sitting upright, the
 * helmet, the mirrors standing out either side, and a single narrow tyre.
 * The rider's hands and neck are a brown skin tone: the people using this app
 * are Ethiopian, and a default pink would be drawing somebody else.
 */
function motorcycleRear({ x, y, w, colour = 'green' }) {
  const { body, edge } = CARS[colour] ?? CARS.green;
  const k = w / 100, skin = '#8a5a34', jacket = '#1f2937';
  return `
  <g transform="translate(${x} ${y}) scale(${k})">
    <rect x="-13" y="-46" width="26" height="46" rx="8" fill="${C.tyre}"/>
    <path d="M -22,-52 C -22,-64 -14,-70 0,-70 C 14,-70 22,-64 22,-52 L 20,-40 L -20,-40 Z"
          fill="${body}" stroke="${edge}" stroke-width="3" stroke-linejoin="round"/>
    <rect x="-11" y="-58" width="22" height="12" rx="4" fill="#ef4444"/>
    <path d="M -30,-96 C -30,-112 -18,-122 0,-122 C 18,-122 30,-112 30,-96 L 26,-64 L -26,-64 Z"
          fill="${jacket}"/>
    <path d="M -30,-104 L -54,-88" stroke="${jacket}" stroke-width="15" stroke-linecap="round"/>
    <path d="M 30,-104 L 54,-88"  stroke="${jacket}" stroke-width="15" stroke-linecap="round"/>
    <circle cx="-56" cy="-86" r="8" fill="${skin}"/><circle cx="56" cy="-86" r="8" fill="${skin}"/>
    <line x1="-58" y1="-92" x2="-64" y2="-108" stroke="#4b5563" stroke-width="5"/>
    <line x1="58"  y1="-92" x2="64"  y2="-108" stroke="#4b5563" stroke-width="5"/>
    <ellipse cx="-66" cy="-112" rx="11" ry="8" fill="${C.glass}" stroke="#4b5563" stroke-width="3.5"/>
    <ellipse cx="66"  cy="-112" rx="11" ry="8" fill="${C.glass}" stroke="#4b5563" stroke-width="3.5"/>
    <rect x="-9" y="-134" width="18" height="16" fill="${skin}"/>
    <circle cx="0" cy="-146" r="26" fill="#e8edf3" stroke="#111827" stroke-width="4"/>
    <path d="M -22,-152 A 24,24 0 0 1 22,-152 Z" fill="#111827"/>
  </g>`;
}



/**
 * A pedestrian seen from above: head, shoulders and the arms swinging out from
 * them. What makes a person readable from overhead is the head sitting proud
 * of a much wider pair of shoulders, so those two shapes carry it and nothing
 * else is drawn. `heading` points the way they are walking.
 *
 * Skin is a brown tone: the people using this app are Ethiopian, and a default
 * pink would be drawing somebody else.
 */
function pedestrian({ x, y, heading = 0, colour = 'blue', scale = 1 }) {
  const { body } = CARS[colour] ?? CARS.blue;
  const skin = '#8a5a34';
  return `
  <g transform="translate(${x} ${y}) rotate(${heading}) scale(${scale})">
    <path d="M -13,-2 L -21,14" stroke="${skin}" stroke-width="7" stroke-linecap="round"/>
    <path d="M 13,-2 L 21,14"  stroke="${skin}" stroke-width="7" stroke-linecap="round"/>
    <path d="M -6,10 L -8,26" stroke="#1f2937" stroke-width="8" stroke-linecap="round"/>
    <path d="M 6,10  L 8,26"  stroke="#1f2937" stroke-width="8" stroke-linecap="round"/>
    <ellipse cx="0" cy="4" rx="14" ry="11" fill="${body}" stroke="#1f2937" stroke-width="2.5"/>
    <circle cx="0" cy="-6" r="9.5" fill="${skin}" stroke="#1f2937" stroke-width="2.5"/>
  </g>`;
}

/**
 * A zebra crossing painted across the carriageway, drawn from above.
 *
 * The stripes run ALONG the road, in the direction the traffic travels, and
 * each one is short. A first version drew them the other way round — long bars
 * lying across the lanes — which is not what the marking looks like on a real
 * road.
 */
function zebraCrossing({ cx, roadTop, roadBottom, length = 70 }) {
  const thickness = 12, gap = 10;
  let out = '';
  for (let y = roadTop + 6; y < roadBottom - thickness - 2; y += thickness + gap) {
    out += `<rect x="${cx - length / 2}" y="${y}" width="${length}" height="${thickness}" fill="${C.line}"/>`;
  }
  return out;
}

function svg(inner, label) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="${label}">
  <defs>
    <marker id="headGo" viewBox="0 0 12 12" refX="9" refY="6" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
      <path d="M0,1 L11,6 L0,11 Z" fill="${C.go}"/>
    </marker>
    <marker id="headWait" viewBox="0 0 12 12" refX="9" refY="6" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
      <path d="M0,1 L11,6 L0,11 Z" fill="${C.wait}"/>
    </marker>
  </defs>${inner}
</svg>
`;
}

// ─── Scene: a wider crossroads, two lanes each way on the vertical road ───────
//
// Used where the question is partly about WHICH LANE a manoeuvre starts from —
// a left turn has to begin from the lane nearest the centre line. Same road
// geometry conventions as crossroads(); only the vertical road is widened.

const VRX = 196, VRW = 248;                  // wide vertical road: 196..444
const LANE = VRW / 4;                        // 62
const SB_OUTER_X = VRX + LANE * 0.5;         // 227  southbound, kerb side
const SB_INNER_X = VRX + LANE * 1.5;         // 289  southbound, centre side
const NB_INNER_X = VRX + LANE * 2.5;         // 351  northbound, centre side — the left-turn lane
const NB_OUTER_X = VRX + LANE * 3.5;         // 413  northbound, kerb side

function crossroadsWide() {
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <g fill="${C.road}">
    <rect x="${VRX}" y="0" width="${VRW}" height="${H}"/>
    <rect x="0" y="${RY}" width="${W}" height="${RH}"/>
  </g>
  <g fill="${C.kerb}">
    <rect x="${VRX - 6}" y="0" width="6" height="${RY}"/><rect x="${VRX + VRW}" y="0" width="6" height="${RY}"/>
    <rect x="${VRX - 6}" y="${RY + RH}" width="6" height="${H - RY - RH}"/><rect x="${VRX + VRW}" y="${RY + RH}" width="6" height="${H - RY - RH}"/>
    <rect x="0" y="${RY - 6}" width="${VRX - 6}" height="6"/><rect x="${VRX + VRW + 6}" y="${RY - 6}" width="${W - VRX - VRW - 6}" height="6"/>
    <rect x="0" y="${RY + RH}" width="${VRX - 6}" height="6"/><rect x="${VRX + VRW + 6}" y="${RY + RH}" width="${W - VRX - VRW - 6}" height="6"/>
  </g>
  <g stroke="${C.line}" stroke-width="4">
    <line x1="${CENTRE_X}" y1="8" x2="${CENTRE_X}" y2="${RY - 10}"/>
    <line x1="${CENTRE_X}" y1="${RY + RH + 10}" x2="${CENTRE_X}" y2="${H - 8}"/>
  </g>
  <g stroke="${C.line}" stroke-width="4" stroke-dasharray="22 18">
    <line x1="${VRX + LANE}" y1="8" x2="${VRX + LANE}" y2="${RY - 10}"/>
    <line x1="${VRX + LANE}" y1="${RY + RH + 10}" x2="${VRX + LANE}" y2="${H - 8}"/>
    <line x1="${VRX + LANE * 3}" y1="8" x2="${VRX + LANE * 3}" y2="${RY - 10}"/>
    <line x1="${VRX + LANE * 3}" y1="${RY + RH + 10}" x2="${VRX + LANE * 3}" y2="${H - 8}"/>
    <line x1="8" y1="${CENTRE_Y}" x2="${VRX - 10}" y2="${CENTRE_Y}"/>
    <line x1="${VRX + VRW + 10}" y1="${CENTRE_Y}" x2="${W - 8}" y2="${CENTRE_Y}"/>
  </g>
  ${tree({ x: 96, y: 76 })}${tree({ x: 552, y: 84, r: 28 })}
  ${tree({ x: 104, y: 376, r: 28 })}${tree({ x: 556, y: 370 })}`;
}

// ─── Scene: a wider crossroads, two lanes each way on the HORIZONTAL road ─────
//
// The mirror of crossroadsWide(). Used so that a left turn is not always drawn
// from the same approach: here the turning car arrives from the left of the
// picture and turns upward, which is a different manoeuvre to read even though
// the law behind it is the same.

const HRY = 96, HRH = 248;                   // wide horizontal road: 96..344
const HLANE = HRH / 4;                       // 62
const H_CENTRE_Y = HRY + HRH / 2;            // 220
const WB_OUTER_Y = HRY + HLANE * 0.5;        // 127  westbound, kerb side
const WB_INNER_Y = HRY + HLANE * 1.5;        // 189  westbound, centre side
const EB_INNER_Y = HRY + HLANE * 2.5;        // 251  eastbound, centre side — the left-turn lane
const EB_OUTER_Y = HRY + HLANE * 3.5;        // 313  eastbound, kerb side

function crossroadsWideAcross() {
  return `
  <rect width="${W}" height="${H}" fill="${C.grass}"/>
  <g fill="${C.road}">
    <rect x="0" y="${HRY}" width="${W}" height="${HRH}"/>
    <rect x="${RX}" y="0" width="${RW}" height="${H}"/>
  </g>
  <g fill="${C.kerb}">
    <rect x="0" y="${HRY - 6}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${HRY - 6}" width="${W - RX - RW - 6}" height="6"/>
    <rect x="0" y="${HRY + HRH}" width="${RX - 6}" height="6"/><rect x="${RX + RW + 6}" y="${HRY + HRH}" width="${W - RX - RW - 6}" height="6"/>
    <rect x="${RX - 6}" y="0" width="6" height="${HRY}"/><rect x="${RX + RW}" y="0" width="6" height="${HRY}"/>
    <rect x="${RX - 6}" y="${HRY + HRH + 6}" width="6" height="${H - HRY - HRH - 6}"/><rect x="${RX + RW}" y="${HRY + HRH + 6}" width="6" height="${H - HRY - HRH - 6}"/>
  </g>
  <g stroke="${C.line}" stroke-width="4">
    <line x1="8" y1="${H_CENTRE_Y}" x2="${RX - 10}" y2="${H_CENTRE_Y}"/>
    <line x1="${RX + RW + 10}" y1="${H_CENTRE_Y}" x2="${W - 8}" y2="${H_CENTRE_Y}"/>
  </g>
  <g stroke="${C.line}" stroke-width="4" stroke-dasharray="22 18">
    <line x1="8" y1="${HRY + HLANE}" x2="${RX - 10}" y2="${HRY + HLANE}"/>
    <line x1="${RX + RW + 10}" y1="${HRY + HLANE}" x2="${W - 8}" y2="${HRY + HLANE}"/>
    <line x1="8" y1="${HRY + HLANE * 3}" x2="${RX - 10}" y2="${HRY + HLANE * 3}"/>
    <line x1="${RX + RW + 10}" y1="${HRY + HLANE * 3}" x2="${W - 8}" y2="${HRY + HLANE * 3}"/>
    <line x1="${CENTRE_X}" y1="8" x2="${CENTRE_X}" y2="${HRY - 10}"/>
    <line x1="${CENTRE_X}" y1="${HRY + HRH + 10}" x2="${CENTRE_X}" y2="${H - 8}"/>
  </g>
  ${tree({ x: 96, y: 46, r: 26 })}${tree({ x: 544, y: 44, r: 24 })}
  ${tree({ x: 100, y: 396, r: 24 })}${tree({ x: 548, y: 394, r: 26 })}`;
}

/**
 * The same numbered disc, but sitting ON the car rather than beside it.
 * A wide road pushes the verge too far from the vehicle for a badge there to
 * be unambiguous, and the official test diagrams label their vehicles the same
 * way. The white ring keeps it readable on a dark or a pale car alike.
 */
function badgeOnCar({ x, y, n }) {
  return `
  <g>
    <circle cx="${x}" cy="${y}" r="17" fill="${C.badge}" stroke="#ffffff" stroke-width="3"/>
    <text x="${x}" y="${y + 6}" font-family="Arial, Helvetica, sans-serif" font-size="19"
          font-weight="bold" fill="#ffffff" text-anchor="middle">${n}</text>
  </g>`;
}

// ─── Scenes ───────────────────────────────────────────────────────────────────

const SCENES = {};

// tr_l1_s3 / rd_l1_s1 — turning left across an oncoming car.
// Car 1 comes up from the south wanting to turn left. Car 2 comes down from the
// north going straight, and has priority. The two arrows deliberately cross:
// that intersection point is the whole reason car 1 must wait, and it is
// visible on screen.
SCENES.tr_l1_s3 = {
  name: 'tr_l1_s3_left_turn_vs_oncoming',
  label: 'Crossroads: a car turning left gives way to an oncoming car going straight',
  build: () => crossroads()
    + car({ x: NORTHBOUND_X, y: 368, heading: 0,   colour: 'yellow', indicate: 'left' })
    + car({ x: SOUTHBOUND_X, y: 96,  heading: 180, colour: 'blue' })
    // arrows before badges, so a badge is never buried under an arrow head
    + arrow({ d: `M ${SOUTHBOUND_X},150 L ${SOUTHBOUND_X},322`, priority: true })
    + arrow({
        d: `M ${NORTHBOUND_X},312 L ${NORTHBOUND_X},${WESTBOUND_Y + 34} `
         + `Q ${NORTHBOUND_X},${WESTBOUND_Y} ${NORTHBOUND_X - 44},${WESTBOUND_Y} `
         + `L 196,${WESTBOUND_Y}`,
        priority: false,
      })
    // badges sit on the verge beside their car, clear of arrows and bodywork
    + badge({ x: NORTHBOUND_X + 62, y: 368, n: 1 })
    + badge({ x: SOUTHBOUND_X - 62, y: 96,  n: 2 }),
};

// rd_l1_s2 — turning left with a third car arriving from the right.
//
// Same core rule as rd_l1_s1 (the left-turner gives way to oncoming traffic),
// but with a third vehicle so the learner meets a busier junction. Car 3 comes
// from the RIGHT, not the left, and that is a correctness decision rather than
// an aesthetic one: with a third car on the LEFT going straight, the three
// give-way duties form a closed loop (we yield to the oncoming car, the
// oncoming car yields to the car on its right, that car yields to us) and the
// law gives no entry order at all — the scene would have no correct answer.
// From the right the order is unambiguous, and both cars simply have priority
// over ours, which keeps the arrow vocabulary binary: green goes, red waits.
SCENES.rd_l1_s2 = {
  name: 'rd_l1_s2_left_turn_from_left_lane',
  label: 'Wide crossroads: a car turning left from the inner lane gives way to an oncoming car',
  build: () => crossroadsWideAcross()
    // The turn is deliberately drawn from a different approach to rd_l1_s1:
    // there the car came up from the bottom, here it arrives from the left and
    // turns upward. Same law, a picture the learner has to read afresh.
    // 0.88 so two cars sit side by side in adjacent lanes with visible air
    // between them; at full size they touch and read as one shape.
    + car({ x: 120, y: EB_INNER_Y, heading: 90,  colour: 'blue',   indicate: 'left', scale: 0.88 })
    + car({ x: 120, y: EB_OUTER_Y, heading: 90,  colour: 'silver', scale: 0.88 })
    + car({ x: 540, y: WB_INNER_Y, heading: 270, colour: 'yellow', scale: 0.88 })
    // arrows before badges, so a badge is never buried under an arrow head
    + arrow({ d: `M 480,${WB_INNER_Y} L 296,${WB_INNER_Y}`, priority: true })
    + arrow({ d: `M 176,${EB_OUTER_Y} L 474,${EB_OUTER_Y}`, priority: true })
    + arrow({
        d: `M 176,${EB_INNER_Y} L ${NORTHBOUND_X - 44},${EB_INNER_Y} `
         + `Q ${NORTHBOUND_X},${EB_INNER_Y} ${NORTHBOUND_X},${EB_INNER_Y - 44} `
         + `L ${NORTHBOUND_X},54`,
        priority: false,
      })
    + badgeOnCar({ x: 120, y: EB_INNER_Y, n: 1 })
    + badgeOnCar({ x: 540, y: WB_INNER_Y, n: 2 })
    + badgeOnCar({ x: 120, y: EB_OUTER_Y, n: 3 }),
};

SCENES.rd_l1_s3 = {
  name: 'rd_l1_s3_give_way_sign',
  label: 'T junction: a give-way sign makes the side-road car wait before turning right onto the main road',
  build: () => teeJunction()
    // The sign stands on the side road's own right-hand verge, level with the
    // car it faces, so there is no doubt which driver it is speaking to.
    + giveWaySign({ x: 442, y: 356, scale: 0.85 })
    + car({ x: NORTHBOUND_X, y: 392, heading: 0,  colour: 'green' })
    + car({ x: 140, y: EASTBOUND_Y, heading: 90,  colour: 'white' })
    // arrows before badges, so a badge is never buried under an arrow head
    // The side-road car turns RIGHT. Two cards already show a left turn, so the
    // manoeuvre here is a different one; what the card teaches is the sign, not
    // the turn. Its arrow runs a little south of the main-road arrow rather than
    // on top of it: the two are joining the same lane, and drawn on one line the
    // red arrowhead simply buried the green arrow and the picture stopped being
    // readable.
    // Both cars are heading into the same lane, so the arrows share its line.
    // They are separated ALONG that line, with the junction as the gap between
    // them: run them side by side and the red arrowhead simply covers the green
    // arrow. Read left to right the picture now says what actually happens —
    // the white car goes through first, the green car follows it out.
    + arrow({ d: `M 204,${EASTBOUND_Y} L 330,${EASTBOUND_Y}`, priority: true })
    + arrow({
        d: `M ${NORTHBOUND_X},344 L ${NORTHBOUND_X},${EASTBOUND_Y + 32} `
         + `Q ${NORTHBOUND_X},${EASTBOUND_Y} ${NORTHBOUND_X + 32},${EASTBOUND_Y} `
         + `L 468,${EASTBOUND_Y}`,
        priority: false,
      })
    + badge({ x: 296, y: 392, n: 1 })
    + badge({ x: 140, y: 212, n: 2 }),
};

SCENES.rd_l2_s1 = {
  name: 'rd_l2_s1_overtake_allowed',
  label: 'Open road: the broken line is on the side of the overtaking driver, so passing the slow vehicle is allowed',
  // This pair travels RIGHT TO LEFT along the far lane, while rd_l2_s2 and
  // rd_l2_s3 run left to right along the near one. Three cards that all showed
  // the same lane and the same direction let a learner recognise a picture
  // instead of reading a situation.
  build: () => openRoad({ brokenLine: 'upper' })
    + car({ x: 496, y: ONCOMING_Y, heading: 270, colour: 'silver' })
    // the vehicle being overtaken is drawn larger, so it reads as the slow one
    + car({ x: 252, y: ONCOMING_Y, heading: 270, colour: 'red', scale: 1.18 })
    + arrow({
        d: `M 432,${ONCOMING_Y} L 378,${ONCOMING_Y} `
         + `Q 334,${ONCOMING_Y} 334,${OURS_Y} `
         + `L 216,${OURS_Y} Q 176,${OURS_Y} 176,${ONCOMING_Y} `
         + `L 94,${ONCOMING_Y}`,
        priority: true,
      })
    + badge({ x: 496, y: ONCOMING_Y - 64, n: 1 })
    + badge({ x: 252, y: ONCOMING_Y - 68, n: 2 }),
};

SCENES.rd_l2_s2 = {
  name: 'rd_l2_s2_overtake_forbidden',
  label: 'Open road: the solid line is on our side, so the slow vehicle may not be overtaken',
  // Deliberately the same road as rd_l2_s1 with the two centre lines swapped.
  // The pair of cards differ in the one detail the rule actually turns on, so a
  // learner cannot answer them from the general look of the picture.
  build: () => openRoad({ brokenLine: 'upper' })
    + car({ x: 150, y: OURS_Y, heading: 90, colour: 'blue' })
    + car({ x: 392, y: OURS_Y, heading: 90, colour: 'yellow', scale: 1.18 })
    + arrow({
        d: `M 214,${OURS_Y} L 268,${OURS_Y} `
         + `Q 312,${OURS_Y} 312,${ONCOMING_Y} `
         + `L 430,${ONCOMING_Y} Q 470,${ONCOMING_Y} 470,${OURS_Y} `
         + `L 552,${OURS_Y}`,
        priority: false,
      })
    + badge({ x: 150, y: OURS_Y + 62, n: 1 })
    + badge({ x: 392, y: OURS_Y + 66, n: 2 }),
};

SCENES.rd_l2_s3 = {
  name: 'rd_l2_s3_overtake_two_wheeler',
  label: 'The road ahead: our car is behind a motorcycle and pulls right out to pass it',
  build: () => roadAhead({ brokenLine: 'lower' })
    + motorcycleRear({ x: laneOurs(depthAt(300)), y: 300, w: 56, colour: 'green' })
    // the path leaves our lane well before the rider and comes back only after
    // — squeezing past inside the lane is exactly what this card argues against
    + arrow({
        d: 'M 436,412 C 386,404 332,372 292,332 C 268,308 262,284 268,248',
        priority: true,
      })
    + carRear({ x: laneOurs(depthAt(420)), y: 420, w: 150, colour: 'white' })
    + badge({ x: 566, y: 388, n: 1 })
    + badge({ x: laneOurs(depthAt(300)) + 58, y: 286, n: 2 }),
};


SCENES.rd_l3_s1 = {
  name: 'rd_l3_s1_pedestrian_approaching_crossing',
  label: 'A pedestrian is walking towards the crossing, so the approaching car must slow and be ready to stop',
  // A city street rather than the open road of the overtaking cards: one lane
  // each way, a zebra across it, and no other vehicle. The only thing to read
  // here is the person, which is the whole point of the card.
  //
  // The person is WALKING ALONG THE PAVEMENT towards the crossing rather than
  // standing still at its mouth, and that is a legal point rather than a
  // cosmetic one. The regulation quoted in the MoT book (pp. 76-77) turns on
  // whether the pedestrian's intention to cross is EVIDENT, and the same book
  // lists what makes it evident: the direction the person is walking and the
  // pace they are walking at, read "before they ever step down into the road".
  // Somebody already halted at the kerb is only the narrowest version of that
  // test, so drawing them mid-approach teaches the rule at its true width.
  //
  // They are on the near pavement, the side the yellow car reaches first.
  build: () => openRoad({ brokenLine: 'lower' })
    + zebraCrossing({ cx: 330, roadTop: OPEN_RY, roadBottom: OPEN_RY + OPEN_RH })
    + car({ x: 128, y: OURS_Y, heading: 90, colour: 'yellow' })
    + pedestrian({ x: 214, y: 348, heading: 0, colour: 'red', scale: 1.15 })
    // The person's arrow carries their whole intended path: along the pavement
    // as far as the crossing, then over the road to the far side. Without that
    // second leg a walker beside a zebra reads as somebody merely passing it.
    + arrow({ d: `M 252,352 L 302,352 Q 330,352 330,316 L 330,112`, priority: true })
    + arrow({ d: `M 192,${OURS_Y} L 252,${OURS_Y}`, priority: false })
    + badge({ x: 128, y: OURS_Y + 62, n: 1 })
    + badge({ x: 214, y: 404, n: 2 }),
};

// ─── Write SVG, then rasterise ────────────────────────────────────────────────

const sceneArg  = process.argv.indexOf('--scene');
const SCENE_KEY = sceneArg >= 0 ? process.argv[sceneArg + 1] : 'tr_l1_s3';
const chosen    = SCENES[SCENE_KEY];
if (!chosen) {
  console.error(`Unknown scene "${SCENE_KEY}". Known: ${Object.keys(SCENES).join(', ')}`);
  process.exit(1);
}

const outArg  = process.argv.indexOf('--out');
const OUT_DIR = outArg >= 0 ? process.argv[outArg + 1] : join(ROOT, 'temp_behavioral');
const NAME    = chosen.name;

const svgText = svg(chosen.build(), chosen.label);
const svgPath = join(OUT_DIR, `${NAME}.svg`);
writeFileSync(svgPath, svgText, 'utf8');
console.log(`SVG: ${svgPath}`);

// 2x so it stays crisp on a phone screen
const { loadImage, createCanvas } = require('canvas');
const img    = await loadImage(Buffer.from(svgText, 'utf8'));
const canvas = createCanvas(img.width * 2, img.height * 2);
canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
const png     = canvas.toBuffer('image/png');
const pngPath = join(OUT_DIR, `${NAME}.png`);
writeFileSync(pngPath, png);
console.log(`PNG: ${pngPath}  (${canvas.width}x${canvas.height}, ${(png.length / 1024).toFixed(1)} KB)`);
